apiVersion: v1
kind: Service
metadata:
  name: pocketbase
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: pocketbase-blackhole
spec:
  ports:
  - port: 80