apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appdomain-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    external-dns.alpha.kubernetes.io/hostname: "*.app.konst.fish"
    external-dns.alpha.kubernetes.io/target: "tetra.shoal.konst.fish"
spec:
  tls:
  - hosts:
    - "*.app.konst.fish"
    secretName: appdomain-tls
  ingressClassName: nginx 
  rules:
  - host: "*.app.konst.fish"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ingress-nginx-defaultbackend
            port:
              number: 80