apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sdot
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/s.konst.fish
  targets:
  - clusterName: guppy
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false