apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressKonstfishTLD
metadata:
  name: check-ingress-for-domain
spec:
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchExpressions:
        - key: tenant
          operator: Exists