{{- $top := . -}}
{{- range $release := .Values.releases -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "pocketbase-{{ $release.name }}"
spec:
  selector:
    app: "pocketbase-{{ $release.name }}"
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
{{ end -}}