{{- $top := . -}}
{{- range $release := .Values.releases -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "pocketbase-{{ $release.name }}"
spec:
  serviceName: "pocketbase-{{ $release.name }}"
  replicas: {{ $top.Values.replicaCount }}
  selector:
    matchLabels:
      app: "pocketbase-{{ $release.name }}"
  template:
    metadata:
      labels:
        app: "pocketbase-{{ $release.name }}"
    spec:
      containers:
      - name: pocketbase
        image: {{ $top.Values.image }}
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: pb-data
          mountPath: "/pb/"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: pb-data
        persistentVolumeClaim:
          claimName: "pocketbase-{{ $release.name }}"
{{ end -}}