apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart: external-dns
  repo: https://charts.hetzner.cloud
  targetNamespace: external-dns
  createNamespace: true
  version: 8.0.2
  valuesContent: |
    txtPrefix: extdns
    provider: pihole
    pihole:
      secretName: pihole
    extraArgs:
      "annotation-filter": "external-dns.alpha.kubernetes.io/hostname"