apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: {{ .Values.targetNamespace }}
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 256Mi
    defaultRequest:
      cpu: "50m"
      memory: 64Mi
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 1m
      memory: 8Mi