apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-object
  namespace: {{ .Values.targetNamespace }}
spec:
  limits:
    configmaps: "300"
    persistentvolumeclaims: "10"
    pods: "100"
    replicationcontrollers: "50"
    secrets: "300"
    services: "300"
    services.loadbalancers: "0"
    services.nodeports: "0"
    
    count/deployments.apps: "100"
    count/replicasets.apps: "100"
    count/statefulsets.apps: "10"
    count/daemonsets.apps: "0"
    
    count/jobs.batch: "10"
    count/cronjobs.batch: "10"

    requests.storage: "30Gi"