apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ .Values.targetNamespace }}
spec:
  hard:
    requests.cpu: {{ .Values.resources.cpu }}
    requests.memory: {{ .Values.resources.memory }}
    limits.cpu: {{ .Values.resources.cpu }}
    limits.memory: {{ .Values.resources.memory }}