apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata: 
  name: tempo-operator
  namespace: operators
spec: 
  channel: alpha 
  name: tempo-operator
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager