apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: 4.11.2
  valuesContent: |
    controller:
      replicaCount: 3
      service:
        annotations:
          load-balancer.hetzner.cloud/location: nbg1
          load-balancer.hetzner.cloud/name: ingress-nginx-tetra
          load-balancer.hetzner.cloud/use-private-ip: true
          # load-balancer.hetzner.cloud/uses-proxyprotocol: true