apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-appdomain-tls
  namespace: ingress-internal
spec:
  secretName: wildcard-internal-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "*.app.konst.fish"
  dnsNames:
  - "*.app.konst.fish"