apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-zero
  namespace: oauth-proxy
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: oauth2-proxy-zero
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: oauth_proxy_zero_cookie_secret
    - secretKey: client-secret
      remoteRef:
        key: oauth_proxy_zero_client_secret
    - secretKey: client-id
      remoteRef:
        key: oauth_proxy_zero_client_id