apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy-zero
  namespace: oauth-proxy
spec:
  chart: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  targetNamespace: oauth-proxy
  version: 7.7.14
  set:
    - name: config.clientID
      value: 
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-zero
            key: oauth_proxy_zero_client_id
    - name: config.clientSecret
      value: 
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-zero
            key: oauth_proxy_zero_client_secret
    - name: config.cookieSecret
      value: 
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-zero
            key: oauth_proxy_zero_cookie_secret
  valuesContent: |
    configFile: |-
      provider="github"
      github_org="shoal-konst-fish"
      github_team="facultative"
      http_address="0.0.0.0:4180"
      upstreams="file:///dev/null"
      email_domains=["*"]
      skip_provider_button=true
      cookie_domains=[".konst.fish"]
      whitelist_domains=[".konst.fish:*"]
      set_xauthrequest=true
      pass_user_headers=true
    ingress:
      enabled: true
      className: nginx
      hosts:
        - sso.konst.fish
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
        external-dns.alpha.kubernetes.io/hostname: "sso.konst.fish"
      tls:
        - secretName: oauth-zero-tls
          hosts:
            - sso.konst.fish

    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-zero-redis
        standalone:
          connectionUrl: redis://oauth2-proxy-zero-redis-headless:6379

    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true