apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-external
  namespace: onprem-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  tls:
  - hosts:
    - jellyfin.konst.fish
    secretName: jellyfin-tls
  ingressClassName: nginx
  rules:
  - host: jellyfin.konst.fish
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              name: http
        path: /
        pathType: ImplementationSpecific