apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaks-data-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi