
helm:
  chart: oci://ghcr.io/cloudtooling/helm-charts/olm
  version: 0.31.0
  values:
    # required for metallb speaker pods
    namespace_psa: 
      enforceLevel: privileged
      enforceVersion: latest
      auditLevel: baseline
      auditVersion: latest
      warnLevel: baseline
      warnVersion: latest
    operator_namespace_psa: 
      enforceLevel: privileged
      enforceVersion: latest