apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-store-gateway
  labels:
    app: thanos-store-gateway
spec:
  selector:
    matchLabels:
      app: thanos-store-gateway
  endpoints:
  - port: http
    interval: 30s