apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  labels:
    app: thanos-store-gateway
spec:
  selector:
    app: thanos-store-gateway
  ports:
  - name: grpc
    port: 10901
  - name: http
    port: 10902
