apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx-internal
  version: 4.11.2
  valuesContent: |
    controller:
      ingressClassByName: true
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-internal
        name: nginx-internal
        default: true
      ingressClass: nginx-internal
      extraArgs:
        default-ssl-certificate: ingress-nginx-internal/wildcard-internal-tls