apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: 4.11.2
  valuesContent: |
    controller:
      ingressClassByName: true
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx
        name: nginx
      service:
        externalIPs: 
          - 92.62.26.112
      replicaCount: 2