apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx-internal
  namespace: ingress-nginx-internal
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx-internal
  version: 4.11.2
  valuesContent: |
    controller:
      ingressClassResource:
        name: nginx-internal
        default: true
      ingressClass: nginx-internal