apiVersion: v1
kind: Service
metadata:
  name: loki-querier-frontend
  labels:
    app: loki-querier-frontend
spec:
  selector:
    app: loki-querier-frontend
  ports:
  - name: http
    port: 3100
    targetPort: 3100