apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-spanmetrics
spec:
  selector:
    matchLabels:
      operator.opentelemetry.io/collector-service-type: headless
  endpoints:
    - port: http-metrics
      interval: 30s