apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  chart: kube-state-metrics
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: monitoring
  version: 5.27.0
  set:
    prometheus.monitor.enabled: "true"
    prometheus.monitor.honorLabels: "true"