apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  config:
    analytics:
      check_for_updates: 'false'
      reporting_enabled: 'false'
    auth:
      disable_login_form: 'true'
      disable_signout_menu: 'true'
    auth.anonymous:
      enabled: 'false'
    auth.proxy:
      enabled: 'true'
      auto_sign_up: 'true'
      enable_login_token: 'false'
      header_name: X-Auth-Request-Email
      headers: >-
        Name:X-Auth-Request-User Email:X-Auth-Request-Email
    users:
      auto_assign_org_role: Admin
      default_theme: light
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:11.6.0