apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-sidecar
  labels:
    app: thanos-sidecar
spec:
  selector:
    matchLabels:
      app: thanos-sidecar
  endpoints:
  - port: http
    interval: 30s