version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
#  - package-ecosystem: "terraform"
#    directory: "/common"
#    schedule:
#      interval: "daily"