apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
spec:
  tenants:
    mode: "static"
  resources:
    total:
      limits:
        cpu: 2000m
        memory: 2Gi
  storage:
    secret:
      name: tempo-objstore-secret
      type: s3
  storageSize: 5Gi
  storageClassName: longhorn
  template:
    queryFrontend:
      jaegerQuery:
        enabled: false