defaultNamespace: kube-system

targetCustomizations:
  - name: local
    clusterName: local # barracuda
    kustomize:
      dir: overlays/barracuda
  - name: tetra
    clusterName: tetra
    kustomize:
      dir: overlays/tetra

# https://github.com/rancher/fleet/issues/3342
ignore:
  conditions:
    - type: "Failed"
      status: "False"