apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  chart: prometheus-node-exporter
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: monitoring
  version: 4.43.0
  valuesContent: |
    prometheus:
      monitor:
        enabled: true
        relabelings:
        - sourceLabels: 
            - __meta_kubernetes_pod_node_name
          targetLabel: node
          action: replace