apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: productpage-service-monitor
spec:
  selector:
    matchLabels:
      app: productpage
  endpoints:
  - port: http
    interval: 30s