resources:
  - ../../base/prometheus
  - ../../base/prometheus/thanos/sidecar
  - ../../base/prometheus/thanos/querier
  - ../../base/exporters/node-exporter
  - ../../base/exporters/kube-state-metrics

patches:
  - path: prometheus/prometheus.yaml
  - patch: |-
      $patch: delete
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDatasource
      metadata:
        name: ds-tempo
  - patch: |-
      $patch: delete
      apiVersion: grafana.integreatly.org/v1beta1
      kind: GrafanaDatasource
      metadata:
        name: ds-loki