apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hits-konst-fish
  namespace: hits-konst-fish
spec:
  secretName: hits-konst-fish
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "hits.konst.fish"
  dnsNames:
  - "hits.konst.fish"