apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: hits.konst.fish
  namespace: hits-konst-fish
spec:
  ref:
    name: hits-konst-fish
    kind: Service
    apiVersion: serving.knative.dev/v1
    # https://github.com/knative/serving/issues/13101
    #name: konstfish-ui-00002
    #apiVersion: v1
  tls:
    secretName: hits-konst-fish