---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: streaks-api-secret
spec:
  encryptedData:
    req_key: AgCWKRuEzFFUJQiT/Du/OopbSvKBD9zFfj6NNZculO/y6/tG2iP+hw0i1tLYm+XDI1eRXq/pI8k/eA+Qn+kYvMzpI0x6pc2Ptdxv0te1DQY1VfkhgwcFXENxnijr+keXuaIdOxJThCduNf4038ZddAw+r1XNhWLVozuDLZFZcPxreqW61hRlBU06xJi/rDrSfawGsPIg/kX09qqwToGl4mYgBhEHFbTel+t4JnoSv51wlAaYf/bdjWn6tohtiZvhfw4tc2c/oNkX6zO8avQ2M5d5j7NyHE0e8QlPS+SYisnQPVMESxotZ7M503S6T0VyRwf2AoydKgXhQggrBqjiZOya2HI5O4UHaLljGRh0cwSSLi2+XmdUHMN6hInrKgKKp0Vr5hTPWWzZHx//Nqv6pdLKdz/FA/iDwe/Au43GtC+pvSobbO/Sq6kWsAbDpFa0/L4GrQPG93FYbpl0ygIGixTLJF6DatKMpnxJeWtQAW1TQ7Cpyo5KdhC9vfbUESawtRUUwzeCHczxkwE5j+7yhZ3oTjktX8bNEpygQtYyVNkJWPwPVgugLGFS+TqDIkQf8HuU3/TKbucEWfbaVmKofdbmruoFv2DNylkcrI4ov7xTMwcjgp69GgtmGjmocGyi8smHcYZcefZJVkVt9GlGLTztMx1paLIhBPPn7pYfJGgxYJBgA0rFoDbRqiA6tB/+n3pujuiROSvzJ8Z+9Wrni5/yMHA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: streaks-api-secret
    type: Opaque