apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: streaks-api-secret
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: streaks-api-secret
    creationPolicy: Owner
  data:
    - secretKey: req_key
      remoteRef:
        key: streaks_api_key