apiVersion: v1
kind: ConfigMap
metadata:
  name: storagekf-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      error_page 404 /404.html;
      error_page 403 /403.html;
      error_page 401 /401.html;

      location / {
        autoindex on;
        try_files $uri $uri/ =404;
      }
    }
