apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objstore-secret
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: thanos-objstore-secret
    creationPolicy: Owner
  data:
    - secretKey: thanos.yaml
      remoteRef:
        key: thanos-objstore-secret