apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: konstfish-ui
  namespace: konstfish-ui
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: ghcr.io/konstfish/ui:latest
        name: user-container
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
          limits:
            cpu: '1'
            memory: 1Gi
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 8080
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100