apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempo
spec:
  tenants:
    mode: "static"
  resources:
    total:
      limits:
        cpu: "2"
        memory: 2Gi
  storage:
    secret:
      name: tempo-objstore-secret
      type: s3
  storageSize: 5Gi
  storageClassName: longhorn-noreplica
  # will be fixed soon ideally, https://github.com/grafana/tempo-operator/pull/1029
  #podSecurityContext:
  #  fsGroup: 10001
  replicationFactor: 1
  template:
    queryFrontend:
      replicas: 2
      jaegerQuery:
        enabled: false
    querier:
      replicas: 2
    ingester:
      replicas: 3
    distributor:
      replicas: 3
  observability:
    metrics:
      createPrometheusRules: false
      createServiceMonitors: true