apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: external-secrets
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/external-secrets
  targets:
  - clusterName: local # barracuda
  - clusterName: guppy
  - clusterName: tetra
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: external-secrets
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/external-secrets
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false