apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: observability
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/observability
  targets:
  - clusterName: local # barracuda 
  - clusterName: tetra
  - clusterName: guppy
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: observability
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/observability