apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: operators
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/operators
  targets:
  - clusterName: barracuda
  - clusterName: tetra
  - clusterName: guppy
  - clusterName: anchovy
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: operators
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/operators
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false