apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: operator-lifecycle-manager
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/operator-lifecycle-manager
  targets:
  - clusterName: barracuda
  - clusterName: tetra
  - clusterName: guppy
  - clusterName: anchovy
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: operator-lifecycle-manager
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/operator-lifecycle-manager