apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "pocketbase-{{ .Values.name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.name }}.api.konst.fish"
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
spec:
  tls:
  - hosts:
    - "{{ .Values.name }}.api.konst.fish"
    secretName: "pocketbase-{{ .Values.name }}-tls"
  ingressClassName: nginx
  rules:
  - host: name.api.konst.fish
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "pocketbase-{{ .Values.name }}"
            port:
              number: 8090