{{- $top := . -}}
{{- range $release := .Values.releases -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "pocketbase-{{ $release.name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    external-dns.alpha.kubernetes.io/hostname: "{{ $release.name }}.api.konst.fish"
spec:
  tls:
  - hosts:
    - "{{ $release.name }}.api.konst.fish"
    secretName: "pocketbase-{{ $release.name }}-tls"
  ingressClassName: nginx
  rules:
  - host: "{{ $release.name }}.api.konst.fish"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "pocketbase-{{ $release.name }}"
            port:
              number: 8090
{{ end -}}