{{- $top := . -}}
{{- range $release := .Values.releases -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pocketbase-{{ $release.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{ end -}}