apiVersion: v1
kind: Service
metadata:
  name: "pocketbase-{{ .Values.name }}"
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
spec:
  selector:
    app: "pocketbase-{{ .Values.name }}"
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090