apiVersion: v1
kind: Service
metadata:
  name: thanos-compactor
  labels:
    app: thanos-compactor
spec:
  selector:
    app: thanos-compactor
  ports:
  - name: grpc
    port: 10901
  - name: http
    port: 10902
