apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: showcase
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  targetNamespace: showcase
  branch: main
  paths:
  - gitops/shoal/showcase
  targets:
  - clusterName: tetra