apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fleet-{{ .Values.tenant }}
  name: fleet-{{ .Values.tenant }}
rules:
  - apiGroups:
    - fleet.cattle.io
    resources:
    - gitrepos
    - bundles
    - clusterregistrationtokens
    - clusters
    - clustergroups
    verbs:
    - '*'