apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-{{ .Values.tenant }}
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - fleet-{{ .Values.tenant }}
    resources:
      - fleetworkspaces
    verbs:
      - '*'