apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: hcloud
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hcloud_token
    - secretKey: network
      value: dmNuLWtmLWh0ei10ZXRyYQ== 