apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: onprem-proxy
  labels:
    app: sonarr
spec:
 ports:
  - protocol: TCP
    name: http
    port: 8989
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonarr
  namespace: onprem-proxy
subsets: 
- addresses:
  - ip: 10.0.1.1
  ports:
  - port: 8989
