apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: {{ .Values.tenant }}
  labels:
    managed-by: shoal
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
  podSelector: {}
  policyTypes:
  - Ingress