apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  namespace: onprem-proxy
spec:
  type: ExternalName
  externalName: 10.0.1.3
  ports:
  - name: http
    port: 9696
