apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-querier-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-querier-frontend
  template:
    metadata:
      labels:
        app: loki-querier-frontend
        type: querier-frontend
    spec:
      serviceAccountName: loki-kube-rbac-proxy
      containers:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.18.2
        args:
          - "--secure-listen-address=0.0.0.0:3100"
          - "--upstream=http://loki-gateway.monitoring.svc.cluster.local/"
          - "--config-file=/etc/kube-rbac-proxy/config.yaml"
          - "--logtostderr=true"
          - "--v=10"
        ports:
          - containerPort: 3100
            name: https
        volumeMounts:
          - name: config
            mountPath: /etc/kube-rbac-proxy
        resources:
          requests:
            memory: 256Mi
            cpu: 150m
          limits:
            memory: 1Gi
            cpu: 500m
      volumes:
        - name: config
          configMap:
            name: loki-kube-rbac-proxy