apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  labels:
    app: pihole-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-exporter
  template:
    metadata:
      labels:
        app: pihole-exporter
    spec:
      containers:
      - name: pihole-exporter
        image: ekofr/pihole-exporter:v0.4.0
        ports:
        - containerPort: 9617
        env:
        - name: PIHOLE_HOSTNAME
          value: "pihole-web"
        - name: PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-password
              key: password
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
