apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-frontend
  labels:
    app: thanos-querier-frontend
spec:
  selector:
    app: thanos-querier-frontend
  ports:
  - name: http
    port: 9090
    targetPort: 9090