apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketbase-data-$name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketbase-public-$name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi