hostname: rancher.konst.fish

# https://slack-archive.rancher.com/t/22906695/wave-has-anyone-had-the-following-error-when-adding-a-generi
agentTLSMode: "system-store"

ingress:
  enabled: true
  tls:
    source: letsEncrypt
  ingressClassName: nginx
  extraAnnotations:
    external-dns.alpha.kubernetes.io/hostname: "rancher.konst.fish"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* /version|/rancherversion {
          deny all;
          return 403;
      }

  
letsEncrypt:
  email: david@konst.fish
  ingress:
    class: nginx