apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: 4.12.0
  valuesContent: |
    controller:
      replicaCount: 3
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "true"
      service:
        annotations:
          load-balancer.hetzner.cloud/location: nbg1
          load-balancer.hetzner.cloud/name: ingress-nginx-barracuda
          load-balancer.hetzner.cloud/use-private-ip: true
          load-balancer.hetzner.cloud/uses-proxyprotocol: true
          load-balancer.hetzner.cloud/hostname: barracuda.shoal.konst.fish
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true