apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  chart: gatekeeper
  repo: https://open-policy-agent.github.io/gatekeeper/charts
  targetNamespace: gatekeeper-system
  version: 3.18.1
  valuesContent: |
    postInstall:
      labelNamespace:
        enabled: false