apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  set:
    defaultSettings.backupTargetCredentialSecret: longhorn-backup-secret
    defaultSettings.backupTarget: s3://shoal-longhorn@eu-central-003/guppy