kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: fleet-tenant-{{ .Values.tenant }}

allowedTargetNamespaces:
{{- range .Values.allowedNamespaces }}
- {{ . }}
{{- end }}