apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: whitelist-portal
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/shoal/whitelist-portal
  targets:
  - clusterName: guppy
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false