defaultNamespace: monitoring

targetCustomizations:
  - name: local
    clusterName: local # barracuda
    kustomize:
      dir: overlays/barracuda
  - name: guppy
    clusterName: guppy
    kustomize:
      dir: overlays/guppy
  - name: tetra
    clusterName: tetra
    kustomize:
      dir: overlays/tetra

# Remove false Tempo Report
ignore:
  conditions:
    - type: Pending
      status: "False"