apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  resources:
    limits:
      cpu: 1400m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi
  replicas: 1
  retention: 7d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        resources:
          requests:
            storage: 30Gi
  thanos:
    image: quay.io/thanos/thanos:v0.38.0
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-secret
  externalLabels:
    cluster: guppy