apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config:
    receivers:
      otlp:
        protocols: 
          grpc: {}
          http: {}

    exporters:
      otlphttp:
        endpoint: https://tempo-ingester-frontend.monitoring.svc:4318
        tls:
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: showcase
          Authorization: Bearer ${env:token}

    processors:
      batch: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp]
          processors: [batch]
  envFrom:
    - secretRef:
        name: otel-sa-token