apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: kube-critical
spec:
  folderRef: kubernetes-ref
  instanceSelector:
    matchLabels:
      app: grafana
  interval: 1m0s
  resyncPeriod: 10m0s
  rules:
  - annotations:
      summary: Node is down
    condition: B
    data:
    - datasourceUid: prometheus1
      model:
        editorMode: code
        expr: kube_node_status_condition{condition="Ready",status="true"}
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
      refId: A
      relativeTimeRange:
        from: 600
    - datasourceUid: __expr__
      model:
        conditions:
        - evaluator:
            params:
            - 0
            - 0
            type: gt
          operator:
            type: and
          query:
            params: []
          reducer:
            params: []
            type: avg
          type: query
        datasource:
          name: Expression
          type: __expr__
          uid: __expr__
        expression: $A != 1
        hide: false
        intervalMs: 1000
        maxDataPoints: 43200
        refId: B
        type: math
      refId: B
    execErrState: Error
    for: 0s
    labels:
      affects: tenants
      severity: critical
      repeat: enabled
      type: kubernetes
    noDataState: NoData
    title: Kubernetes Node Status
    uid: de4206z03zd34c