apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: critical
spec:
  folderRef: kubernetes-ref
  instanceSelector:
    matchLabels:
      app: grafana
  interval: 1m
  rules:
  - uid: de4206z03zd34c
    title: Kubernetes Node Status
    condition: B
    for: 0s
    data:
      - refId: A
        relativeTimeRange:
          from: 600
          to: 0
        datasourceUid: prometheus1
        model:
          editorMode: code
          expr: kube_node_status_condition{condition="Ready",status="true"}
          instant: true
          intervalMs: 1000
          legendFormat: __auto
          maxDataPoints: 43200
          range: false
          refId: A
      - refId: B
        datasourceUid: __expr__
        model:
          conditions:
              - evaluator:
                  params:
                      - 0
                      - 0
                  type: gt
                operator:
                  type: and
                query:
                  params: []
                reducer:
                  params: []
                  type: avg
                type: query
          datasource:
              name: Expression
              type: __expr__
              uid: __expr__
          expression: $A != 1
          hide: false
          intervalMs: 1000
          maxDataPoints: 43200
          refId: B
          type: math
    noDataState: NoData
    execErrState: Error
    isPaused: false
    annotations:
      summary: Node is down
    labels:
      type: kubernetes
      severity: high
      affects: tenants