apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: moderate
spec:
  folderRef: kubernetes-ref
  instanceSelector:
    matchLabels:
      app: grafana
  interval: 5m
  rules:
    - uid: ce426ijbwtyioe
      title: Kubernetes Node Disk Usage
      condition: B
      for: 0s
      data:
        - refId: A
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: thanos1
          model:
            editorMode: code
            expr: (1 - sum by(node) (node_filesystem_avail_bytes{mountpoint="/"}) / sum by(node) (node_filesystem_size_bytes{mountpoint="/"})) * 100
            instant: true
            intervalMs: 1000
            legendFormat: __auto
            maxDataPoints: 43200
            range: false
            refId: A
        - refId: B
          datasourceUid: __expr__
          model:
            conditions:
                - evaluator:
                    params:
                        - 0
                        - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
            datasource:
                name: Expression
                type: __expr__
                uid: __expr__
            expression: $A > 85
            intervalMs: 1000
            maxDataPoints: 43200
            refId: B
            type: math
      noDataState: NoData
      execErrState: Error
      annotations:
        summary: Node Disk Capacity >85%
      labels:
        severity: moderate
        type: kubernetes
      isPaused: false
