apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      "functions.konst.fish": ""
    network:
      "ingress.class": "istio.ingress.networking.knative.dev"
    istio:
      knative-ingress-gateway:
        selector:
          istio: ingressgateway
        servers:
        - hosts:
          - "*"
          port:
            name: http
            number: 80
            protocol: HTTP
          tls:
            httpsRedirect: true
        - hosts:
          - "*"
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: wildcard-functions-tls