apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      "functions.konst.fish": ""
    network:
      defaultExternalScheme: "https"
    istio:
      external-gateways: |
        - name: knative-ingress-gateway
          namespace: knative-serving
          service: istio-ingress.istio-system.svc.cluster.local
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingressgateway
        servers:
        - hosts:
          - "*"
          port:
            name: http
            number: 80
            protocol: HTTP
        - hosts:
          - "*"
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: wildcard-functions-tls