apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  controller-custom-certs:
    name: wildcard-functions-tls
    type: Secret
  config:
    domain:
      "functions.konst.fish": ""