resources:
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-dns
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: david@konst.fish
        privateKeySecretRef:
          name: letsencrypt-dns
        solvers:
        - dns01:
            cloudflare:
              apiTokenSecretRef:
                name: cloudflare-api-token-secret
                key: api-token
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-http
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: david@konst.fish
        privateKeySecretRef:
          name: letsencrypt-http
        solvers:
        - http01:
            ingress:
              class: nginx
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: appdomain
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: appdomain@shoal.konst.fish
        privateKeySecretRef:
          name: appdomain
        solvers:
        - http01:
            ingress:
              class: nginx
              serviceType: ClusterIP