apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: 4.12.0
  valuesContent: |
    controller:
      replicaCount: 3
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true