apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: pihole
spec:
  chart: external-dns
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: pihole
  createNamespace: true
  version: 8.0.2
  valuesContent: |
    provider: pihole
    policy: upsert-only
    txtOwnerId: "kf"
    pihole:
      server: http://pihole-web.pihole.svc.cluster.local
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
    serviceAccount:
      create: true
      name: "external-dns"
    ingressClassFilters:
      - nginx-internal
    extraArgs:
      "annotation-filter": "external-dns.alpha.kubernetes.io/hostname"