apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: onprem-proxy
  labels:
    app: synology
spec:
 ports:
  - protocol: TCP
    name: http
    port: 5000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: synology
  namespace: onprem-proxy
subsets: 
- addresses:
  - ip: 10.0.1.3
  ports:
  - port: 5000
