apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-rancher-cluster
rules:
  - apiGroups: ["management.cattle.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-rancher-cluster-view-binding
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-rancher-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempo-operator-rancher-cluster-view-binding
subjects:
  - kind: ServiceAccount
    name: tempo-operator-controller-manager
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-rancher-cluster