apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-internal-tls
  namespace: ingress-nginx-internal
spec:
  secretName: wildcard-internal-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: "*.konst.fish"
  dnsNames:
  - "*.konst.fish"
  - "*.int.konst.fish"