---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-metrics-write
subjects:
- kind: ServiceAccount
  name: otel-sa
  namespace: showcase