defaults:
  kind: DaemonSet
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

  # this messes with my port mapping, doing the same stuff manually below
  # networkGateway: guppy

  service:
    type: NodePort
    ports:
      - name: status-port
        port: 15021
        targetPort: 15021
        nodePort: 32021
      - name: tls
        port: 15443
        targetPort: 15443
        nodePort: 32443
      - name: tls-istiod
        port: 15012
        targetPort: 15012
        nodePort: 32012
      - name: tls-webhook
        port: 15017
        targetPort: 15017
        nodePort: 32017

  env:
    ISTIO_META_REQUESTED_NETWORK_VIEW: guppy