apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: '9000'
    prometheus.io/scrape: 'true'
  labels:
    app: minio
  name: minio
spec:
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
    - name: pool-0
      servers: 3
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      volumesPerServer: 2
  requestAutoCert: false
  env:
    - name: MINIO_DOMAIN
      value: "minio.konst.fish"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://console.minio.konst.fish"
    - name: MINIO_SERVER_URL
      value: "https://minio.konst.fish"