apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: ds-loki
spec:
  instanceSelector:
    matchLabels:
      app: "grafana"
  datasource:
    name: loki
    type: loki
    uid: loki1
    access: proxy
    basicAuth: false
    url: http://loki:3100
    isDefault: false
    jsonData:
      "tlsSkipVerify": true
      "timeInterval": "5s"