apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-kube-rbac-proxy
data:
  config.yaml: |+
    authorization:
      rewrites:
        byHttpHeader:
          name: "X-Scope-OrgID"
      resourceAttributes:
        apiVersion: v1
        resource: namespace
        subresource: metrics
        namespace: "{{ .Value }}"