apiVersion: v1
kind: Service
metadata:
  name: tempo-querier-frontend
  labels:
    app: tempo-querier-frontend
spec:
  selector:
    app: tempo-querier-frontend
  ports:
  - name: http
    port: 3200
    targetPort: 3200