apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.36.1
        args:
          - query
          - --http-address=0.0.0.0:9090
          - --store=prometheus-operated:10901
          - --store=thanos-store-gateway:10901
          - --query.auto-downsampling
        ports:
        - name: http
          containerPort: 9090
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 500m