apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-querier
  labels:
    app: thanos-querier
spec:
  selector:
    matchLabels:
      app: thanos-querier
  endpoints:
  - port: http
    interval: 30s