apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      serviceAccountName: kube-rbac-proxy
      containers:
      - name: thanos-querier
        image: quay.io/thanos/thanos:v0.35.0
        args:
          - query
          - --http-address=0.0.0.0:9090
          - --store=prometheus-operated:10901
        ports:
        - name: http
          containerPort: 9090
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 500m
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.16.1
        args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--config-file=/etc/kube-rbac-proxy/config.yaml"
          - "--logtostderr=true"
          - "--v=10"
        ports:
          - containerPort: 8443
            name: https
        volumeMounts:
          - name: config
            mountPath: /etc/kube-rbac-proxy
        resources:
          requests:
            memory: 256Mi
            cpu: 150m
          limits:
            memory: 1Gi
            cpu: 500m
      - name: prom-label-enforcer
        image: quay.io/prometheuscommunity/prom-label-proxy:v0.8.1
        imagePullPolicy: Always
        args:
          - "--insecure-listen-address=127.0.0.1:8080"
          - "--upstream=http://127.0.0.1:9090/"
          - "--label=namespace"
          - "--enable-label-apis=true"
        resources:
          requests:
            memory: 256Mi
            cpu: 150m
          limits:
            memory: 1Gi
            cpu: 500m
        ports:
        - containerPort: 8080
          name: https
      volumes:
        - name: config
          configMap:
            name: kube-rbac-proxy