apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prom-label-proxy-client
  namespace: monitoring
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ['get', 'list', 'watch', 'create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prom-label-proxy-client
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prom-label-proxy-client
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitoring