
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-rbac-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      serviceAccountName: kube-rbac-proxy
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.4.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://localhost:8080/"
            - "--config-file=/etc/kube-rbac-proxy/config.yaml"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
          volumeMounts:
            - name: config
              mountPath: /etc/kube-rbac-proxy
        - name: prom-label-enforcer
          image: quay.io/coreos/prom-label-proxy:v0.1.0
          imagePullPolicy: Always
          args:
            - "--insecure-listen-address=127.0.0.1:8080"
            - "--upstream=http://prometheus-k8s.monitoring.svc:9090/"
            - "--label=namespace"
      volumes:
        - name: config
          configMap:
            name: kube-rbac-proxy