apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pocketbase-{{ .Values.name }}"
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi