targetCustomizations:
  - name: local
    clusterName: local # barracuda
    kustomize:
      dir: overlays/barracuda
  - name: guppy
    clusterName: guppy
    kustomize:
      dir: overlays/guppy
  - name: tetra
    clusterName: tetra
    kustomize:
      dir: overlays/tetra
  - name: anchovy
    clusterName: anchovy
    kustomize:
      dir: overlays/anchovy