apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups: []
  labels:
    type: backup
  name: backup-daily
  parameters: {}
  retain: 7
  task: backup