resources:
  - https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/crds.yaml
  - https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/olm.yaml