apiVersion: v1
kind: Service
metadata:
  name: tempo-ingester-frontend
  labels:
    app: tempo-ingester-frontend
spec:
  selector:
    app: tempo-ingester-frontend
  ports:
  - name: http
    port: 4317
    targetPort: 4317