apiVersion: v1
kind: Service
metadata:
  name: tempo-ingester-frontend
  labels:
    app: tempo-ingester-frontend
spec:
  selector:
    app: tempo-ingester-frontend
  ports:
  - name: https
    port: 4318
    targetPort: 4318