apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoDNSAnnotation
metadata:
  name: no-external-dns
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Deployment", "Service"]
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchExpressions:
        - key: tenant
          operator: Exists