apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CertManagerClusterIssuerBlock
metadata:
  name: block-cert-manager-cluster
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Deployment", "Service"]
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchExpressions:
        - key: tenant
          operator: Exists
  parameters:
    allowedClusterIssuers:
      - appdomain