apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressKonstfishTLD
metadata:
  name: ingresskonstfishtld
spec:
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchExpressions:
      - key: tenant
        operator: In
        values:
        - 'true'