apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: telegram
spec:
  name: telegram
  type: telegram
  instanceSelector:
    matchLabels:
      app: grafana
  valuesFrom:
    - targetPath: bottoken
      valueFrom:
        secretKeyRef:
          key: bottoken
          name: telegram-secret
    - targetPath: chatid
      valueFrom:
        secretKeyRef:
          key: chatid
          name: telegram-secret
  settings:
    bottoken: <templated>
    chatid: <templated>
    disable_notification: false
    disable_web_page_preview: false
    protect_content: false
    parse_mode: Markdown
    message: |
      {{ define "default.message" }}{{ if gt (len .Alerts.Firing) 0 }}🔥 Firing
      {{ template "alerts.summarize" .Alerts.Firing }}{{ if gt (len .Alerts.Resolved) 0 }}

      {{ end }}{{ end }}{{ if gt (len .Alerts.Resolved) 0 }}✅ Resolved
      {{ template "alerts.summarize" .Alerts.Resolved }}{{ end }}{{ end }}

      {{ define "alerts.summarize" -}}
        {{ range . -}}
          - {{ if .Labels.node }}[{{ .Labels.node }}]{{ end }} {{ index .Annotations "summary" }}
        {{ end }}
      {{ end }}

      {{ template "default.message" . }}
