apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: projects
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/projects
  correctDrift:
    enabled: false
  insecureSkipTLSVerify: false