apiVersion: management.cattle.io/v3
builtin: false
context: project
description: ""
displayName: Project Tenant
external: false
hidden: false
kind: RoleTemplate
metadata:
  name: project-tenant
roleTemplateNames:
- read-only
rules:
# Rancher
- apiGroups:
  - ui.cattle.io
  resources:
  - navlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.cattle.io
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - apprevisions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - clusterevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertrules
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertgroups
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectloggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectcatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectmonitorgraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplateversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cattle.io
  resources:
  - prometheus
  verbs:
  - view
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resourceNames:
  - local
  resources:
  - clusters
  verbs:
  - get


# Kubernetes
## kubectl
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  - secrets
  - services/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
### ServiceAccount
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
### Metrics
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  # - nodes
  verbs:
  - get
  - list
  - watch

## Cluster
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch

## Config
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - replicationcontrollers
  - replicationcontrollers/scale
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  - services/status
  verbs:
  - get
  - list
  - watch

## Compute
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - deployments
  - deployments/scale
  - deployments/status
  - replicasets
  - replicasets/scale
  - replicasets/status
  - statefulsets
  - statefulsets/scale
  - statefulsets/status
  verbs:
  - get
  - list
  - watch
### Jobs
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - cronjobs/status
  - jobs
  - jobs/status
  verbs:
  - get
  - list
  - watch
### Scaling
#### Auto
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
#### Manual
- apiGroups:
  - extensions
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - deployments/status
  - replicasets/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  - horizontalpodautoscalers/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - poddisruptionbudgets/status
  verbs:
  - get
  - list
  - watch

## Networking
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  # - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingresses/status
  - networkpolicies
  verbs:
  - get
  - list
  - watch

# Operator/CRD Stuff
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - grafanaalertrulegroups.grafana.integreatly.org
  - grafanadashboards.grafana.integreatly.org
  - grafanadatasources.grafana.integreatly.org
  - grafanafolders.grafana.integreatly.org
  - grafanas.grafana.integreatly.org

  - instrumentations.opentelemetry.io
  - opentelemetrycollectors.opentelemetry.io

  - podmonitors.monitoring.coreos.com
  # - probes.monitoring.coreos.com
  # - prometheusagents.monitoring.coreos.com
  - prometheusrules.monitoring.coreos.com
  - scrapeconfigs.monitoring.coreos.com
  - servicemonitors.monitoring.coreos.com
  resources:
  - customresourcedefinitions
  verbs:
  - get

## OLM
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  - catalogsources 
  - installplans
  - subscriptions
  - operatorgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  - packagemanifests/icon
  verbs:
  - get
  - list
  - watch

## Monitoring
### Custom
- apiGroups: [""]
  resources:
  - namespace/metrics
  verbs:
    - get
    - create
### Alerting
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagerconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - issuers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
### Metrics
- apiGroups:
  - monitoring.coreos.com
  resources:
  # - prometheusrules
  - scrapeconfigs
  - servicemonitors
  - podmonitors
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
### Grafana
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanaalertrulegroups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanadashboards
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanadatasources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanafolders
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - grafana.integreatly.org
  resources:
  - grafanas
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
### OpenTelemetry
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  - instrumentations
  # - opampbridges
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

## Cert Manager
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - certificaterequests
  - issuers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - acme.cert-manager.io
  resources:
  - challenges
  - orders
  verbs:
  - get
  - list
  - watch

## Sealed Secrets
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

## Rancher
- apiGroups:
  - ui.cattle.io
  resources:
  - navlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.cattle.io
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - apprevisions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - clusterevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertrules
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertgroups
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectloggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectcatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectmonitorgraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplateversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cattle.io
  resources:
  - prometheus
  verbs:
  - view
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resourceNames:
  - local
  resources:
  - clusters
  verbs:
  - get

## Helm Charts
- apiGroups:
  - helm.cattle.io
  resources:
  - helmcharts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete