apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  baseImage: grafana/grafana:10.1.9
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
