apiVersion: management.cattle.io/v3
builtin: false
context: project
description: ""
displayName: Project Tenant
external: false
hidden: false
kind: RoleTemplate
metadata:
  generation: 1
  name: project-tenant
roleTemplateNames:
- edit
rules:
- apiGroups:
  - ui.cattle.io
  resources:
  - navlinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.cattle.io
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - apprevisions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - clusterevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertrules
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertgroups
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectloggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - clustercatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectcatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectmonitorgraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplateversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cattle.io
  resources:
  - prometheus
  verbs:
  - view
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - prometheusrules
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - sidecars
  - virtualservices
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - apikeys
  - authorizations
  - checknothings
  - circonuses
  - deniers
  - fluentds
  - handlers
  - kubernetesenvs
  - kuberneteses
  - listcheckers
  - listentries
  - logentries
  - memquotas
  - metrics
  - opas
  - prometheuses
  - quotas
  - quotaspecbindings
  - quotaspecs
  - rbacs
  - reportnothings
  - rules
  - solarwindses
  - stackdrivers
  - statsds
  - stdios
  verbs:
  - '*'
- apiGroups:
  - authentication.istio.io
  resources:
  - policies
  verbs:
  - '*'
- apiGroups:
  - rbac.istio.io
  resources:
  - rbacconfigs
  - serviceroles
  - servicerolebindings
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  verbs:
  - '*'
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - operations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resourceNames:
  - local
  resources:
  - clusters
  verbs:
  - get