apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
  namespace: onprem-proxy
spec:
  type: ExternalName
  externalName: 10.0.1.3
  ports:
  - name: http
    port: 9091
