apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hcloud-csi
  namespace: kube-system
spec:
  chart: hcloud-csi
  repo: https://charts.hetzner.cloud
  targetNamespace: kube-system
  version: 2.9.0