apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy-negative
  namespace: oauth-proxy
spec:
  chart: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  targetNamespace: oauth-proxy
  version: 7.7.27
  valuesContent: |
    config:
      existingSecret: oauth2-proxy-negative
      configFile: |-
        provider="github"
        github_org="shoal-konst-fish"
        github_team="facultative"
        http_address="0.0.0.0:4180"
        upstreams="file:///dev/null"
        email_domains=["*"]
        skip_provider_button=true
        cookie_domains=[".konst.fish"]
        whitelist_domains=[".konst.fish:*"]
        set_xauthrequest=true
        pass_user_headers=true
    ingress:
      enabled: true
      className: nginx
      hosts:
        - sson.konst.fish
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
        external-dns.alpha.kubernetes.io/hostname: "sson.konst.fish"
      tls:
        - secretName: oauth-negative-tls
          hosts:
            - sson.konst.fish

    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-negative-redis
        standalone:
          connectionUrl: redis://oauth2-proxy-negative-redis-headless:6379

    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true