apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-negative
  namespace: oauth-proxy
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: oauth2-proxy-negative
    creationPolicy: Owner
  data:
    - secretKey: oauth_proxy_negative_cookie_secret
      remoteRef:
        key: oauth_proxy_negative_cookie_secret
    - secretKey: oauth_proxy_negative_client_secret
      remoteRef:
        key: oauth_proxy_negative_client_secret
    - secretKey: oauth_proxy_negative_client_id
      remoteRef:
        key: oauth_proxy_negative_client_id