apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: ui.konst.fish
  namespace: konstfish-ui
spec:
  ref:
    name: konstfish-ui
    kind: Service
    apiVersion: serving.knative.dev/v1
    # https://github.com/knative/serving/issues/13101
    #name: konstfish-ui-00002
    #apiVersion: v1
  tls:
    secretName: ui-konst-fish