apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aquarium-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: aquarium.app.konst.fish
    http:
      paths:
      - path: /sprites/v1
        pathType: Prefix
        backend:
          service:
            name: aquarium-sprite
            port:
              number: 4001