hostname: rancher.konst.fish

ingress:
  enabled: true
  tls:
    source: letsEncrypt
  ingressClassName: nginx
  extraAnnotations:
    external-dns.alpha.kubernetes.io/hostname: "rancher.konst.fish"
  
letsEncrypt:
  email: david@konst.fish
  ingress:
    class: nginx