apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-{{ .Values.tenant }}
  namespace: fleet-{{ .Values.tenant }}
subjects:
- kind: User
  name: {{ .Values.tenantId }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fleet-{{ .Values.tenant }}
  apiGroup: rbac.authorization.k8s.io