apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: main
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  route:
    receiver: telegram
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: telegram
        continue: true
        object_matchers:
          - - repeat
            - =
            - enabled
        repeat_interval: 1h