apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: appdomain
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: appdomain@shoal.konst.fish
    privateKeySecretRef:
      name: appdomain
    solvers:
    - http01:
        ingress:
          class: nginx
          serviceType: ClusterIP