apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acl-manager
rules:
  - apiGroups: [""]
    resources:
    - secrets
    - configmaps
    verbs:
    - get
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses/status
    verbs:
    - get
    - patch
    - update