apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acl-manager
subjects:
- kind: ServiceAccount
  name: acl-manager
  namespace: acl-manager
roleRef:
  kind: ClusterRole
  name: acl-manager
  apiGroup: rbac.authorization.k8s.io