apiVersion: v1
kind: Service
metadata:
  name: acl-manager
  labels:
    app.kubernetes.io/name: acl-manager
spec:
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: acl-manager