controller:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  replicaCount: 3
  minAvailable: 2
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  hostNetwork: false
  hostPort:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
#  config:
#    custom-http-errors: "404,500,502,503"
defaultBackend:
  enabled: true
  image:
    repository: ghcr.io/konstfish/custom-default-backend
    tag: "latest"
    pullPolicy: Always
    readOnlyRootFilesystem: false