controller:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  kind: DaemonSet
  service:
    type: NodePort
  hostNetwork: true
  hostPort:
    enabled: true
#  config:
#    custom-http-errors: "404,500,503"

defaultBackend:
  enabled: true
  image:
    repository: ghcr.io/konstfish/custom-default-backend
    tag: "latest"
    pullPolicy: Always
    readOnlyRootFilesystem: false