clusterName: teleport.konst.fish
proxyListenerMode: multiplex


acme: false
acmeEmail: david@konst.fish

proxy:
  service:
    type: ClusterIP

service:
  type: ClusterIP

ingress:
  enabled: true
  spec:
    ingressClassName: nginx

highAvailability:
  certManager:
    enabled: true
    issuerName: letsencrypt-dns
    issuerKind: ClusterIssuer

annotations:
  ingress:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    external-dns.alpha.kubernetes.io/hostname: "teleport.konst.fish"
