apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  external_services:
    prometheus:
      url: "http://thanos-querier.monitoring.svc:9090"
    grafana:
      enabled: true
      internal_url: 'http://grafana-service.monitoring.svc:3000'
      external_url: 'https://grafana.tetra.konst.fish'