apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fishbot-config
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: fishbot-config
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: fishbot_neon_postgres
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: fishbot_discord_token