apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: monitoring
spec:
  chart: loki
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  version: 6.24.0
  set:
    deploymentMode: SimpleScalable
    monitoring.serviceMonitor.enabled: "true"
    tableManager.retention_deletes_enabled: "true"
    tableManager.retention_period: 720h
  valuesContent: |-
    loki:
      # kubectl get namespaces --no-headers -o custom-columns=":metadata.name" | tr '\n' '|' | sed 's/|$//'
      auth_enabled: true
      querier:
        multi_tenant_queries_enabled: true
      storage:
        bucketNames:
          chunks: ${bucket}
          ruler: ${bucket}
          admin: ${bucket}
        type: s3
        s3:
          endpoint: ${endpoint}
          secretAccessKey: "${secretAccessKey}"
          accessKeyId: "${accessKeyId}"
      schemaConfig:
        configs:
          - from: 2024-04-01
            object_store: s3
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
    # https://github.com/grafana/loki/issues/12218
    backend:
      persistence: 
        storageClass: longhorn-noreplica
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom: 
        - secretRef:
            name: loki-objstore-secret
    read:
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom: 
        - secretRef:
            name: loki-objstore-secret
    write:
      extraArgs:
        - -config.expand-env=true
      extraEnvFrom: 
        - secretRef:
            name: loki-objstore-secret
      persistence: 
        storageClass: longhorn-noreplica