apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart: promtail
  repo: https://grafana.github.io/helm-charts
  targetNamespace: monitoring
  version: 6.16.6
  set:
    serviceMonitor.enabled: "true"
  valuesContent: |-
    config:
      snippets:
        pipelineStages:
          - cri: {}
          - match:
              selector: '{namespace=~"showcase|kfs-playground"}'
              stages:
                - tenant:
                    label: "namespace"
          - output:
              source: message