apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-objstore-secret
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: loki-objstore-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: loki-objstore-secret