apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: hetzner-cloud-controller-manager
  namespace: fleet-default
spec:
  repo: https://github.com/konstfish/shoal
  branch: main
  paths:
  - gitops/infra/hetzner/cloud-controller-manager
  targets:
  - clusterName: local # barracuda
  - clusterName: tetra