apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: projects
  namespace: fleet-local
spec:
  repo: https://github.com/konstfish/shoal
  branch: gitopsv2
  paths:
  - gitops/projects/kustomization-local.yaml
  - gitops/projects/base
  insecureSkipTLSVerify: false
  correctDrift:
    enabled: false