name: Build Quartz Site
on:
 push:
   branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs
            .github
          fetch-depth: 0
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q docs; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
      - name: Build
        uses: konstfish/quartz-build-action@main
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        with:
          source: docs
          quartz_config: .github/quartz.config.ts
          quartz_layout: .github/quartz.layout.ts
          quartz_icon: .github/icon.png
          quartz_banner: .github/og-image.png
      - name: Upload artifact
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        uses: actions/upload-pages-artifact@v1
      - name: Deploy to GitHub Pages
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
