name: Validate Kustomize

on:
  push:
    branches: ['*']
    paths:
      - gitops/**
  pull_request:
    branches: [ main ]
    paths:
      - gitops/**

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Validate Kustomize
      run: |
        find . -name kustomization.yaml | sort -n | tr '\n' ' ' | 
        while IFS= read -r -d ' ' file; do
          dir=$(dirname "$file")
          kustomize build "$dir" > /dev/null
          if [ $? -eq 0 ]; then
            echo "✅ $dir" | sed 's/\.\/gitops\///'
          else
            echo "❌ $dir" | sed 's/\.\/gitops\///'
            exit 1
          fi
        done
