apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  external-domain-tls: Enabled
  namespace-wildcard-cert-selector: |-
    matchExpressions:
    - key: "networking.knative.dev/disableWildcardCert"
      operator: "NotIn"
      values: ["true"]